export type {
  CoreClip,
  CoreInsertFx,
  CoreMeta,
  CoreMidiNote,
  CoreMixer,
  CoreMixerBus,
  CoreMixerChannel,
  CoreFxSend,
  CoreState,
  CoreTrack,
  CoreTransport,
  TimeSignature,
  TransportState,
} from "./types";

export {
  createProject,
  setName,
  setTempo,
  setTimeSignature,
  addTrack,
  removeTrack,
  renameTrack,
  selectTrack,
  setTrackColor,
  setTrackPreset,
  setTrackEngine,
  reorderTracks,
  addClip,
  removeClip,
  moveClip,
  resizeClip,
  trimClip,
  setClipNotes,
  addNote,
  removeNote,
  updateNote,
  addMixerChannel,
  removeMixerChannel,
  setChannelVolume,
  setChannelPan,
  setChannelMute,
  setChannelSolo,
  setChannelInsertFx,
  setChannelSend,
  addMixerBus,
  setBusVolume,
  setMasterVolume,
  play,
  pause,
  stop,
  setPosition,
  toggleMetronome,
  DEFAULT_BPM,
  DEFAULT_PPQN,
} from "./commands";

export { CoreHistory, type CoreHistoryEntry } from "./history";

export {
  createCoreStore,
  type CoreListener,
  type CoreReducer,
  type CoreStore,
} from "./store";

export {
  toSchema,
  fromSchema,
  timeSignatureToString,
  timeSignatureFromString,
  collectMidiNotes,
} from "./schema-convert";
